---

- name: stop firewalld
  service: name=firewalld state=stopped enabled=no

- name: modify the limits
  template: src=limits.conf dest=/etc/security/limits.conf

###############################
#  暂时不提供
###############################
#- name: modify the limits
#  template: src=k8s.conf dest=/etc/sysctl.d/k8s.conf
#
#- name: apply  kernel setting
#  shell: sysctl -p

###############################
#系统优化配置
###############################

- name: modify the kernel set vars
  template: src=chinacloud.conf dest=/etc/sysctl.d/chinacloud.conf

- name: apply  kernel setting
  shell: sysctl -p

- name: offline  swap
  shell: swapoff -a
  ignore_errors: yes

- name: create repo bak directory
  file: path=/etc/yum.repos.d/bak state=directory mode=0755

- name: remove all base repository
  shell: mv /etc/yum.repos.d/*.repo  /etc/yum.repos.d/bak
  ignore_errors: yes

- name: add mir2 private yum repository
  template: src=mir2.repo dest=/etc/yum.repos.d/mir2.repo


- name: clean all
  shell: yum clean all

# 内网情况下不能执行"yum update -y", 屏蔽此步骤
# - name: upgrade all packages
#   yum: name=* state=latest update_cache=yes

###############################
# 升级内核
###############################

- name: remove  kernel-tools  kernel-tools-libs
  shell: yum -y remove kernel-tools kernel-tools-libs

- name: update kernel version to 4.4.121-1
  shell: yum -y install kernel-lt
  when: ansible_kernel < "4.4.121-1"

- name: install   kernel-lt-tools  kernel-lt-tools-libs
  shell: yum -y install kernel-lt-tools  kernel-lt-tools-libs

- name: update GRUB boot image
  shell: sed -i "s#^GRUB_DEFAULT.*#GRUB_DEFAULT=0#g" /etc/default/grub && grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_kernel < "4.4.121-1"

###############################
# install base software
###############################

- name: create /tmp/docker-install directory
  file: path=/tmp/docker-install state=directory mode=0755

- name: install docker engine
  shell: yum -y install docker-engine

- name: copy owner docker binary
  copy: src=docker/ dest=/usr/bin/  mode=0755 backup=yes

- name: copy pause-amd64.tar
  copy: src=pause-amd64.tar dest=/tmp/docker-install/pause-amd64.tar

- name: install socat
  shell: yum -y install socat ipvsadm

- name: install mount.nfs
  shell: yum -y install mount.nfs

- name: install ceph client
  shell: yum -y install ceph

- name: install node_exporter
  shell: yum -y install golang-github-prometheus-node_exporter

- name: copy owner node_exporter binary
  copy: src=node-exporter/ dest=/usr/sbin/  mode=0755 backup=yes

- name: push node_exporter sysconfig
  template: src=node_exporter.sysconfig dest=/etc/sysconfig/node_exporter

- name: push node_exporter seivice
  template: src=node_exporter.service.j2 dest=/usr/lib/systemd/system/node_exporter.service

- name: daemon reload
  shell: systemctl daemon-reload

- name: start node_exporter
  service: name=node_exporter state=restarted enabled=yes

# - name: remove docker engine
#   shell: yum -y remove docker-engine docker-engine-selinux
#   tags: uninstall