- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ hostvars[item].ansible_fqdn }}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }}    {{ hostvars[item].ansible_fqdn }}'
    state: present
  with_items: '{{ groups["all"] }}'

- name: Build host record for registry
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{registry_host}}$'
    line: '{{ hostvars[groups["registries"][0]].ansible_default_ipv4.address }}    {{ registry_host }}'
    state: present
  when: groups["registries"]
