# Step 1, 关闭防火墙, 安装Docker
- include: base.yml
# Step 2, 安装容器镜像仓库
- include: registry.yml
# Step 3, 部署Etcd集群
- include: etcd.yml
# Step 4, 部署Kubernetes ssh安全配置
- include: k8s-ss1.yml
# Step 5, 部署Kubernetes Master节点
- include: masters.yml
# Step 6, 部署Kubernetes Minion节点
- include: minions.yml
# Step 7, 部署Skydns
- include: dns.yml
