########################################################################################################################
# 配置常用变量 docker_data_vol 是用于docker配置overlay2卷的分区，是必须修改的变量,且整个集群中必须使用统一的物理磁盘分区，
#请按现场实际预留的磁盘分区进行修改 (必须)  （备注： 这里的vdb是裸磁盘，也可以分区是vdb1 但是 分区必须自行使用分区工具分配好）
########################################################################################################################

docker_data_vol: /dev/vdb

########################################################################################################################
# 配置常用变量 harbor_data_vol 是用于Harbor存储镜像的卷分区，是必须修改的变量,只存在于Harbor（registry）主机
#场实际预留的磁盘分区进行修改 （必须） （备注： 这里的vdc是裸磁盘，也可以分区是vdc1 但是 分区必须自行使用分区工具分配好）
########################################################################################################################

harbor_data_vol: /dev/vdc

########################################################################################################################
# reposerver 为存放包含k8s安装文件（chinacloud-repo）的yum源地址，默认与Harbor（registry）放在一起
# 所以默认不需要填写。
# 如果没有安装registry并使用其他机器部署了yum源服务， 请修改 reposerver 为你部署yum源地址
########################################################################################################################

reposerver:

########################################################################################################################
# master_vip 是在master配置了HA的情况下，添加新node节点时需要的master  vip，master_vip_port为vip上承载
# k8s_apiserver的端口， 默认是8080， 但是vip与k8s的apiserver部署在同一台机子上时，不能使用同一端口， 可能发生改变。
# 在 master 没有配置HA时， 不要填写该IP与Port，
# 如果master配置HA， 此变量master_vip必填； 如果master_vip承载主机与k8s masters相同，master_vip_port参数必填且不能是8080
# 如果 不 部署 master 的 HA  请不要填写下面的变量 ！！！！！！
########################################################################################################################

master_vip:
master_vip_port:


########################################################################################################################
# flannel 的配置选项： flannel_eth 是在多网卡多网络运行时指定flannel运行的网卡上；
#（即管理网络，业务网络，存储网络分开部署时，flannel_eth将填写为业务网络使用的网卡）
# 如果是单网络，则不需要填写（默认不填写）
########################################################################################################################

flannel_eth: